# Generated by Django 3.2.5 on 2021-08-28 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0003_auto_20210807_1402'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Client',
        ),
    ]
